[VOLKSZAEHLER]
ip = volkszaehler
uuid_import = fcdffee0-65eb-11e9-a4ed-dff87061b9a1
uuid_export = 2aa3d860-65ec-11e9-97b5-a32a65faf9d5

#[MEC]
#ip = 10.0.0.8
#url = http://10.0.0.8/wizard/public/api/measurements
#statusurl = http://10.0.0.8/setup/api/status
#username = admin
#password = topsecret
#intervall = 1
